import { ENDPOINTS } from '../../../common/utilities';
import { mock } from '../../../common/utilities';
import axios from 'axios';


export  function injectFakeAxios(){
  const openRoles = [
    {
      role_name: 'Designer',
      role_desc: 'Responsible for creating visually appealing designs.',
      role_skills: ['Creative thinking', 'Graphic design software'],
      start_date: '01-01-2023',
      end_date: '31-12-2023',
      managerID: 1,
      department: 'IT',
      country: 'Singapore',
    },
    {
      role_name: 'Manager',
      role_desc: 'Oversees team activities and ensures project success.',
      role_skills: ['Leadership', 'Project management', 'Communication'],
      start_date: '15-02-2023',
      end_date: '30-11-2023',
      managerID: 2,
      department: 'Sales',
      country: 'Malaysia',
    },
    {
      role_name: 'Analyst',
      role_desc: 'Analyzes data to provide insights and support decision-making.',
      role_skills: ['Data analysis', 'Statistics', 'Excel'],
      start_date: '10-03-2023',
      end_date: '20-10-2023',
      managerID: 3,
      department: 'IT',
      country: 'Thailand',
    },
    {
      role_name: 'Developer',
      role_desc: 'Codes and maintains software applications.',
      role_skills: ['Programming', 'Software development', 'Problem-solving'],
      start_date: '05-04-2023',
      end_date: '15-09-2023',
      managerID: 4,
      department: 'IT',
      country: 'Indonesia',
    },
    {
      role_name: 'Engineer',
      role_desc: 'Designs and develops technical solutions.',
      role_skills: ['Engineering principles', 'Technical design'],
      start_date: '20-05-2023',
      end_date: '10-08-2023',
      managerID: 5,
      department: 'Engineering',
      country: 'Vietnam',
    },
    {
      role_name: 'Architect',
      role_desc: 'Designs and plans architectural structures.',
      role_skills: ['Architectural design', 'Blueprints'],
      start_date: '12-06-2023',
      end_date: '25-07-2023',
      managerID: 6,
      department: 'Engineering',
      country: 'Philippines',
    },
    {
      role_name: 'Writer',
      role_desc: 'Creates written content for various purposes.',
      role_skills: ['Writing', 'Editing', 'Research'],
      start_date: '08-07-2023',
      end_date: '30-06-2023',
      managerID: 7,
      department: 'Content',
      country: 'Singapore',
    },
    {
      role_name: 'Coordinator',
      role_desc: 'Coordinates activities and schedules within a team.',
      role_skills: ['Organization', 'Communication', 'Teamwork'],
      start_date: '19-08-2023',
      end_date: '15-11-2023',
      managerID: 8,
      department: 'Operations',
      country: 'Malaysia',
    },
    {
      role_name: 'Consultant',
      role_desc: 'Provides expert advice and guidance to clients.',
      role_skills: ['Consulting', 'Problem-solving', 'Client relations'],
      start_date: '25-09-2023',
      end_date: '20-12-2023',
      managerID: 9,
      department: 'Consulting',
      country: 'Thailand',
    },
    {
      role_name: 'Supervisor',
      role_desc: 'Oversees and guides team members in daily tasks.',
      role_skills: ['Leadership', 'Supervision', 'Team management'],
      start_date: '14-10-2023',
      end_date: '05-03-2024',
      managerID: 10,
      department: 'Management',
      country: 'Indonesia',
    },
    {
      role_name: 'Technician',
      role_desc: 'Performs technical tasks and troubleshoots issues.',
      role_skills: ['Technical skills', 'Problem-solving'],
      start_date: '30-11-2023',
      end_date: '10-05-2024',
      managerID: 11,
      department: 'IT',
      country: 'Vietnam',
    },
    {
      role_name: 'Coordinator',
      role_desc: 'Coordinates activities and schedules within a team.',
      role_skills: ['Organization', 'Communication', 'Teamwork'],
      start_date: '19-12-2023',
      end_date: '15-03-2024',
      managerID: 12,
      department: 'Operations',
      country: 'Philippines',
    },
    {
      role_name: 'Designer',
      role_desc: 'Responsible for creating visually appealing designs.',
      role_skills: ['Creative thinking', 'Graphic design software'],
      start_date: '08-01-2024',
      end_date: '30-06-2024',
      managerID: 13,
      department: 'IT',
      country: 'Singapore',
    },
    {
      role_name: 'Manager',
      role_desc: 'Oversees team activities and ensures project success.',
      role_skills: ['Leadership', 'Project management', 'Communication'],
      start_date: '12-02-2024',
      end_date: '25-09-2024',
      managerID: 14,
      department: 'Sales',
      country: 'Malaysia',
    },
    {
      role_name: 'Analyst',
      role_desc: 'Analyzes data to provide insights and support decision-making.',
      role_skills: ['Data analysis', 'Statistics', 'Excel'],
      start_date: '18-03-2024',
      end_date: '15-12-2024',
      managerID: 15,
      department: 'IT',
      country: 'Thailand',
    },
    {
      role_name: 'Developer',
      role_desc: 'Codes and maintains software applications.',
      role_skills: ['Programming', 'Software development', 'Problem-solving'],
      start_date: '22-04-2024',
      end_date: '10-08-2024',
      managerID: 16,
      department: 'IT',
      country: 'Indonesia',
    },
    {
      role_name: 'Engineer',
      role_desc: 'Designs and develops technical solutions.',
      role_skills: ['Engineering principles', 'Technical design'],
      start_date: '05-05-2024',
      end_date: '20-07-2024',
      managerID: 17,
      department: 'Engineering',
      country: 'Vietnam',
    },
    {
      role_name: 'Architect',
      role_desc: 'Designs and plans architectural structures.',
      role_skills: ['Architectural design', 'Blueprints'],
      start_date: '19-06-2024',
      end_date: '30-10-2024',
      managerID: 18,
      department: 'Engineering',
      country: 'Philippines',
    },
    {
      role_name: 'Writer',
      role_desc: 'Creates written content for various purposes.',
      role_skills: ['Writing', 'Editing', 'Research'],
      start_date: '30-07-2024',
      end_date: '15-02-2025',
      managerID: 19,
      department: 'Content',
      country: 'Singapore',
    },
    {
      role_name: 'Consultant',
      role_desc: 'Provides expert advice and guidance to clients.',
      role_skills: ['Consulting', 'Problem-solving', 'Client relations'],
      start_date: '10-08-2024',
      end_date: '20-03-2025',
      managerID: 20,
      department: 'Consulting',
      country: 'Thailand',
    },
  ];
  
  console.log(openRoles);
  

mock.onGet(ENDPOINTS.listings).reply(200, openRoles)

  
}
  