name: Linting

on:
  # Run on every push, pull, or merge to any branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # For manual triggering on GitHub web UI
  workflow_dispatch:
    inputs:
      custom_dispatch:
        description: 'Manually trigger linting'
        required: false

jobs:
  # Lint on ubuntu-latest
  lint-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8 on Linux
        run: flake8 backend/
