name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # For manual triggering on GitHub web UI
  workflow_dispatch:
    inputs:
      custom_dispatch:
        description: 'Manually trigger testing'
        required: false

jobs:
  # Unit tests on Windows
  unit-tests-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests on Windows
        run: python backend/unit_tests.py

      - name: Upload unit test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: backend/unit_tests.txt

  # Integration tests on Windows
  