name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  # For manual triggering on GitHub web UI
  workflow_dispatch:
    inputs:
      custom_dispatch:
        description: 'Manually trigger testing'
        required: false

jobs:
  # Unit tests on Windows
  unit-tests-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests on Windows
        run: python backend/unit_tests.py

  # Unit tests on Linux
  unit-tests-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests on Linux
        run: python backend/unit_tests.py

  # Unit tests on macOS
  unit-tests-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests on macOS
        run: python backend/unit_tests.py

  # Integration tests on Windows
  # Integration tests on Linux
  # Integration tests on macOS
